select id, `FROMINSTITUTION_ID`, `INSTITUTION_ID` , `TOINSTITUTION_ID`, `CREDITCOMPANY_ID`, `BILLDATE`,  `CREATEDAT`, `NETTOTAL`, `SALEVALUE`, `BILLTYPE`, `DTYPE`, `DEPARTMENT_ID`, `CREATEDAT`,`BILLDATE` from bill
where `CREDITCOMPANY_ID` is not null
order by id desc limit 50;